[project]
name = "work-force-360"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg>=0.30.0",
    "boto3>=1.42.57",
    "email-validator>=2.3.0",
    "fastapi>=0.118.3",
    "firebase-admin>=7.1.0",
    "geoalchemy2>=0.18.1",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "shapely>=2.1.2",
    "slowapi>=0.1.9",
    "sqlalchemy[asyncio]>=2.0.44",
    "uvicorn>=0.37.0",
]
