"""Added firebase uid in worker model

Revision ID: 018fee109b07
Revises: d29948b749ee
Create Date: 2026-02-13 13:17:18.325182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "018fee109b07"
down_revision: Union[str, Sequence[str], None] = "d29948b749ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workers", sa.Column("firebase_uid", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "firebase_uid")
    # ### end Alembic commands ###
