"""Updated location column in company_addresses table

Revision ID: 06049b45ae4c
Revises: a04862bcd17d
Create Date: 2026-02-05 14:05:54.108053

"""

from typing import Sequence, Union

from alembic import op
from geoalchemy2 import Geography
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06049b45ae4c"
down_revision: Union[str, Sequence[str], None] = "a04862bcd17d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_addresses",
        sa.Column(
            "location",
            Geography(geometry_type="POINT", srid=4326),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_addresses", "location")
    # ### end Alembic commands ###
