"""Updated Latitude and longitude column

Revision ID: 06049b45ae4c
Revises: a04862bcd17d
Create Date: 2026-02-05 14:05:54.108053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06049b45ae4c'
down_revision: Union[str, Sequence[str], None] = 'a04862bcd17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_addresses', sa.Column('latitude', sa.String(), nullable=False))
    op.add_column('company_addresses', sa.Column('longitude', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_addresses', 'longitude')
    op.drop_column('company_addresses', 'latitude')
    # ### end Alembic commands ###
