"""Added wage column in sub_category_skills table

Revision ID: 3185d836784c
Revises: d06eb2564747
Create Date: 2026-03-12 12:02:17.541158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3185d836784c'
down_revision: Union[str, Sequence[str], None] = 'd06eb2564747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_category_skills', sa.Column('wage', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_category_skills', 'wage')
    # ### end Alembic commands ###
