"""Changed the customer registration model and schema

Revision ID: 49b62436696d
Revises: c80c674f79b2
Create Date: 2026-01-08 13:08:04.014370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49b62436696d"
down_revision: Union[str, Sequence[str], None] = "c80c674f79b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("auth_phone", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("contact_phone", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("contact_email", sa.String(), nullable=True))
    op.alter_column(
        "companies", "contact_person_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(op.f("companies_email_key"), "companies", type_="unique")
    op.create_unique_constraint(None, "companies", ["contact_email"])
    op.drop_column("companies", "email")
    op.drop_column("companies", "phone")
    op.alter_column(
        "company_documents", "document_type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "company_documents", "document_url", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "company_documents", "document_url", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "company_documents", "document_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column(
        "companies",
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "companies",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "companies", type_="unique")
    op.drop_constraint(None, "companies", type_="unique")
    op.create_unique_constraint(
        op.f("companies_email_key"),
        "companies",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "companies", "contact_person_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("companies", "contact_email")
    op.drop_column("companies", "contact_phone")
    op.drop_column("companies", "auth_phone")
    # ### end Alembic commands ###
