"""Corrected relationalship between models

Revision ID: 537823d2ba70
Revises: e2b10bd329af
Create Date: 2026-02-19 11:42:58.421183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537823d2ba70'
down_revision: Union[str, Sequence[str], None] = 'e2b10bd329af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_skill_categories', 'category_name')
    op.drop_column('worker_skill_subcategories', 'sub_category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_skill_subcategories', sa.Column('sub_category_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('worker_skill_categories', sa.Column('category_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
