"""Added and modified industry_name and industry id

Revision ID: 566b9607a5d8
Revises: e8d5256e4c81
Create Date: 2026-01-10 12:38:40.968365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566b9607a5d8'
down_revision: Union[str, Sequence[str], None] = 'e8d5256e4c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry_name', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('industry_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('companies_industry_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'industry_types', ['industry_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_industry_fkey'), 'companies', 'industry_types', ['industry'], ['id'], ondelete='RESTRICT')
    op.drop_column('companies', 'industry_id')
    op.drop_column('companies', 'industry_name')
    # ### end Alembic commands ###
