"""Create job posting page

Revision ID: 626f0d6115ea
Revises: a6a053c3521e
Create Date: 2026-02-12 16:37:08.177015

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "626f0d6115ea"
down_revision: Union[str, Sequence[str], None] = "a6a053c3521e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_postings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("skill_category_id", sa.UUID(), nullable=False),
        sa.Column("sub_category_id", sa.UUID(), nullable=True),
        sa.Column("industry_type_id", sa.UUID(), nullable=True),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("work_address", sa.Text(), nullable=True),
        sa.Column("nearby_landmark", sa.Text(), nullable=True),
        sa.Column(
            "scheduled_start_datetime", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("scheduled_end_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_duration", sa.String(), nullable=True),
        sa.Column("duration_type", sa.String(), nullable=True),
        sa.Column("shift", sa.String(), nullable=True),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workers", sa.Integer(), nullable=False),
        sa.Column("experience_required", sa.String(), nullable=True),
        sa.Column("wage", sa.Integer(), nullable=False),
        sa.Column("expected_total", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("language_preference", sa.String(), nullable=True),
        sa.Column("tool_provided", sa.Boolean(), nullable=False),
        sa.Column("tool_details", sa.Text(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "posted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["industry_type_id"],
            ["industry_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_category_id"],
            ["category_skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_category_id"],
            ["sub_category_skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """
    CREATE INDEX IF NOT EXISTS idx_job_postings_location
    ON job_postings USING gist (location);
"""
    )

    op.create_index(
        "idx_job_scheduled_start",
        "job_postings",
        ["scheduled_start_datetime"],
        unique=False,
    )
    op.create_index("idx_job_status", "job_postings", ["status"], unique=False)
    op.alter_column(
        "companies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "companies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "company_addresses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "company_bank_details",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "company_documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "company_documents",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "company_bank_details",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "company_addresses",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "companies",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "companies",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "category_skills", type_="foreignkey")
    op.drop_index("idx_job_status", table_name="job_postings")
    op.drop_index("idx_job_scheduled_start", table_name="job_postings")
    op.drop_index(
        "idx_job_postings_location", table_name="job_postings", postgresql_using="gist"
    )
    op.drop_table("job_postings")
    # ### end Alembic commands ###
