"""corrected industry and skill model

Revision ID: 64561712d5b8
Revises: 40972d7aa1ef
Create Date: 2026-01-03 09:13:33.512683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64561712d5b8'
down_revision: Union[str, Sequence[str], None] = '40972d7aa1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_types', 'description')
    op.alter_column('sub_category_skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('sub_category_skills', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_category_skills', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('sub_category_skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('industry_types', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
