"""Created work category ans sub category table

Revision ID: 828c9c950535
Revises: af002bd61f5c
Create Date: 2026-02-19 10:57:59.608806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '828c9c950535'
down_revision: Union[str, Sequence[str], None] = 'af002bd61f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_skill_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('category_skill_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=150), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_skill_id'], ['category_skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'category_skill_id', name='uq_worker_category_unique')
    )
    op.create_index(op.f('ix_worker_skill_categories_category_skill_id'), 'worker_skill_categories', ['category_skill_id'], unique=False)
    op.create_index(op.f('ix_worker_skill_categories_worker_id'), 'worker_skill_categories', ['worker_id'], unique=False)
    op.create_table('worker_skill_subcategories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('sub_category_skill_id', sa.UUID(), nullable=False),
    sa.Column('sub_category_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sub_category_skill_id'], ['sub_category_skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'sub_category_skill_id', name='uq_worker_subcategory_unique')
    )
    op.create_index(op.f('ix_worker_skill_subcategories_sub_category_skill_id'), 'worker_skill_subcategories', ['sub_category_skill_id'], unique=False)
    op.create_index(op.f('ix_worker_skill_subcategories_worker_id'), 'worker_skill_subcategories', ['worker_id'], unique=False)
    op.drop_table('test_companies')
    op.drop_index(op.f('ix_worker_skill_selections_worker_id'), table_name='worker_skill_selections')
    op.drop_table('worker_skill_selections')
    op.drop_column('workers', 'category_name')
    op.drop_column('workers', 'category_id')
    op.drop_column('workers', 'years')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('category_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_table('worker_skill_selections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sub_category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sub_category_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('worker_skill_selections_worker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('worker_skill_selections_pkey'))
    )
    op.create_index(op.f('ix_worker_skill_selections_worker_id'), 'worker_skill_selections', ['worker_id'], unique=False)
    op.create_table('test_companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_companies_pkey'))
    )
    op.drop_index(op.f('ix_worker_skill_subcategories_worker_id'), table_name='worker_skill_subcategories')
    op.drop_index(op.f('ix_worker_skill_subcategories_sub_category_skill_id'), table_name='worker_skill_subcategories')
    op.drop_table('worker_skill_subcategories')
    op.drop_index(op.f('ix_worker_skill_categories_worker_id'), table_name='worker_skill_categories')
    op.drop_index(op.f('ix_worker_skill_categories_category_skill_id'), table_name='worker_skill_categories')
    op.drop_table('worker_skill_categories')
    # ### end Alembic commands ###
