"""company id

Revision ID: 86716cb505bd
Revises: f3a1c5b2d9e0
Create Date: 2026-04-11 11:11:25.451535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86716cb505bd"
down_revision: Union[str, Sequence[str], None] = "f3a1c5b2d9e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_postings", sa.Column("company_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_job_postings_company_id"), "job_postings", ["company_id"], unique=False
    )
    op.create_foreign_key(None, "job_postings", "companies", ["company_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job_postings", type_="foreignkey")
    op.drop_index(op.f("ix_job_postings_company_id"), table_name="job_postings")
    op.drop_column("job_postings", "company_id")
    # ### end Alembic commands ###
