"""Added Contact number country code

Revision ID: a04862bcd17d
Revises: ca9ac982300c
Create Date: 2026-01-24 13:36:23.970186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04862bcd17d'
down_revision: Union[str, Sequence[str], None] = 'ca9ac982300c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('contact_country_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'contact_country_code')
    # ### end Alembic commands ###
