"""updated matching login

Revision ID: ad04abe201b6
Revises: 537823d2ba70
Create Date: 2026-02-19 17:47:25.899229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad04abe201b6'
down_revision: Union[str, Sequence[str], None] = '537823d2ba70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('assigned_worker_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_job_postings_assigned_worker_id'), 'job_postings', ['assigned_worker_id'], unique=False)
    op.create_foreign_key(None, 'job_postings', 'workers', ['assigned_worker_id'], ['id'])
    op.add_column('workers', sa.Column('is_online', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('workers', sa.Column('is_available', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('workers', sa.Column('current_job_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'current_job_id')
    op.drop_column('workers', 'is_available')
    op.drop_column('workers', 'is_online')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_index(op.f('ix_job_postings_assigned_worker_id'), table_name='job_postings')
    op.drop_column('job_postings', 'assigned_worker_id')
    # ### end Alembic commands ###
