"""Added status_approval_message_shown field in worker and customer table

Revision ID: d06eb2564747
Revises: 328dd16bbefc
Create Date: 2026-03-02 16:57:08.846111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06eb2564747'
down_revision: Union[str, Sequence[str], None] = '328dd16bbefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('status_approval_message_shown', sa.Boolean(), nullable=True))
    op.add_column('workers', sa.Column('status_approval_message_shown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'status_approval_message_shown')
    op.drop_column('companies', 'status_approval_message_shown')
    # ### end Alembic commands ###
