"""Added country code

Revision ID: d251dcfdc180
Revises: 018fee109b07
Create Date: 2026-02-13 13:39:36.112548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d251dcfdc180"
down_revision: Union[str, Sequence[str], None] = "018fee109b07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job_postings",
        "experience_required",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="experience_required::integer",
    )
    op.create_index(
        op.f("ix_worker_documents_worker_id"),
        "worker_documents",
        ["worker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_worker_skill_selections_worker_id"),
        "worker_skill_selections",
        ["worker_id"],
        unique=False,
    )
    op.add_column(
        "workers", sa.Column("country_code", sa.String(length=10), nullable=True)
    )
    op.create_unique_constraint(None, "workers", ["firebase_uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workers", type_="unique")
    op.drop_column("workers", "country_code")
    op.drop_index(
        op.f("ix_worker_skill_selections_worker_id"),
        table_name="worker_skill_selections",
    )
    op.drop_index(op.f("ix_worker_documents_worker_id"), table_name="worker_documents")
    op.alter_column(
        "job_postings",
        "experience_required",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
