"""Update type in job posting

Revision ID: e4d1a0bd68fa
Revises: 622300cc55a2
Create Date: 2026-02-12 19:23:46.125793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4d1a0bd68fa'
down_revision: Union[str, Sequence[str], None] = '622300cc55a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'skill_category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('job_postings', 'workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'tool_provided',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('job_postings', 'posted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'posted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_postings', 'tool_provided',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('job_postings', 'workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'skill_category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
